name: Deploy Frontend to AWS

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Build Frontend
        run: npm run build

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: dist  

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: frontend-build
          path: dist

      - name: Setup SSH Key
        run: |
          echo "$AWS_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
  
      - name: Deploy to AWS EC2
        env:
          AWS_HOST: ${{ secrets.AWS_HOST }}
          USER: ubuntu
        run: |
          scp -i private_key.pem -r dist ubuntu@$AWS_HOST:/home/ubuntu/frontend
          ssh -i private_key.pem ubuntu@$AWS_HOST << 'EOF'
            sudo mv /home/ubuntu/frontend/dist /var/www/frontend
            sudo systemctl restart nginx
          EOF
  
